#!/usr/bin/env bash

set -eux

rm test.db* || true

BINARY_NAME="$(./scripts/build)"

go build \
  -tags netgo \
  -o "${BINARY_NAME}" \
  main.go

TEST_FILE="$(./scripts/make-data-file)"
readonly TEST_FILE

"./${BINARY_NAME}" "${TEST_FILE}"
