#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

./dev-scripts/run-go-tests --quick
./dev-scripts/check-go-formatting

npm run check-format
npm run lint
./node_modules/.bin/mocha --recursive handlers/static/js/.tests/*.test.js
