# -*- mode: ruby -*-
# vi: set ft=ruby :

# Memory limit is passed via environment variable
VM_MEMORY = ENV['VM_MEMORY'] || '512'

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "picoshare-perf"

  # Forward PicoShare port
  config.vm.network "forwarded_port", guest: 4001, host: 4001

  # Use rsync for synced folder (doesn't require NFS)
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/", "test-files/", ".vagrant/"]

  config.vm.provider "virtualbox" do |vb|
    vb.memory = VM_MEMORY
    vb.cpus = 1
    vb.name = "picoshare-perf-test"
  end

  config.vm.provider "libvirt" do |lv|
    lv.memory = VM_MEMORY
    lv.cpus = 1
    lv.management_network_guest_ipv6 = false
    lv.management_network_autostart = true
    lv.qemu_use_agent = true
  end

  # Minimal provisioning - just ensure we can run the binary
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -qq
    apt-get install -y -qq procps curl
  SHELL
end
