#!/bin/bash

# Exit script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

./node_modules/.bin/prettier --check .
./node_modules/.bin/eslint ./**/*.js
./node_modules/.bin/mocha --recursive handlers/static/js/.tests/*.test.js
