#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands.
set -x

if [[ -z $1 ]]; then
  MODE='prod'
else
  MODE="$1"
fi

PLATFORM="${TARGETPLATFORM:-linux/amd64}"

# Exit on unset variable.
set -u

GO_BUILD_TAGS=()
EXTRA_FLAGS=()
BINARY='./bin/picoshare'
if [[ "${MODE}" == 'prod' ]]; then
  GO_BUILD_TAGS+=('netgo')
  EXTRA_FLAGS=('-ldflags' '-w -extldflags "-static"')
else
  BINARY="${BINARY}-${MODE}"
  GO_BUILD_TAGS+=("${MODE}")
fi
readonly BINARY
readonly GO_BUILD_TAGS
readonly EXTRA_FLAGS

export readonly GOOS='linux'
if [ "${PLATFORM}" = 'linux/amd64' ]; then
  GOARCH='amd64'
elif [ "${PLATFORM}" = 'linux/arm/v7' ]; then
  GOARCH='arm'
elif [ "${PLATFORM}" = 'linux/arm64' ]; then
  GOARCH='arm64'
else
  echo "Unsupported platform: ${PLATFORM}"
  exit 1
fi
export readonly GOARCH

go build \
  -tags "${GO_BUILD_TAGS[@]}" \
  "${EXTRA_FLAGS[@]}" \
  -o "${BINARY}" \
  cmd/picoshare/main.go
