#!/bin/bash

# Check for trailing whitespace

# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

# Change directory to repository root.
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "${SCRIPT_DIR}/.."

while read -r line; do
  if grep \
    "\s$" \
    --line-number \
    --with-filename \
    --binary-files=without-match \
    "${line}"; then
    echo "ERROR: Found trailing whitespace";
    exit 1;
  fi
done < <(git ls-files)
