#!/usr/bin/env bash

# Run this to enable all git hooks for this project.

set -x
set -e
set -u

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

# If there's an existing symlink, remove it.
if [[ -L .git/hooks ]]
then
  rm .git/hooks
fi

# If it's a regular directory, remove all files.
if [[ -d .git/hooks ]]
then
  rm -rf .git/hooks
fi

ln -s -f ../dev-scripts/git-hooks .git/hooks
