#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

FUZZ_TIME="150s"

go test \
  -fuzztime "${FUZZ_TIME}" \
  -fuzz FuzzGuestUpload \
  github.com/mtlynch/picoshare/v2/handlers
