#!/usr/bin/env bash

# Run a single Go test with the specified test function name.

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Fail when piped commands fail.
set -o pipefail

readonly TEST_NAME="$1"

go test \
  -tags=netgo,osusergo,sqlite_json \
  -fullpath \
  -run "^${TEST_NAME}\$" \
  ./...
