#!/usr/bin/env bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

DOCKER_BUILDKIT=1 \
  docker build -t picoshare .

if [[ -f .env.dev ]]; then
  set +x
  # shellcheck disable=SC1091
  . .env.dev
  set -x
fi

PS_SHARED_SECRET=somepassword

docker rm -f picoshare || true

docker run \
  --env "PORT=4002" \
  --env "PS_SHARED_SECRET=${PS_SHARED_SECRET}" \
  --publish "0.0.0.0:4002:4002" \
  --name picoshare \
  --memory 256m \
  picoshare
