#!/usr/bin/env bash

# Exit on first failing command.
set -e

# Exit on unset variable.
set -u

# Echo commands
set -x

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

# Install air if it's not present.
if ! command -v air &> /dev/null; then
    readonly AIR_VERSION="v1.61.7"
    go install "github.com/air-verse/air@${AIR_VERSION}"
fi

# Run air for hot reloading.
air
